# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageRepo: sampleapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)
          latest

          
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: ubuntu-latest
    steps: 
- task: Docker@2
  inputs:
    containerRegistry: 'service connection'
    repository: '$(imageRepo)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
    tags: |
      $(tag)
      latest